### ISSUE TITLE
Update rest-on-couch?

### ISSUE THREAD

**Issue by targos** [cheminfo/roc-docker-mydb#1]
We are currently at version 8.
In theory, we could update to at least version 12 (v13 requires a more recent CouchDB) but I don't know why we haven't done that before

/cc @stropitek (this is the config for c6h6.org)

**Comment by stropitek** [comment]
There hasn't been a particular reason for not updating.

I can take care of it once I know how to access the server.

**Comment by stropitek** [comment]
Update after https://github.com/cheminfo/rest-on-couch/issues/374

**Comment by targos** [comment]
Moved to other repo
